import {
  Bot,
  Braces,
  Calculator,
  CalendarDays,
  Code2,
  Crop,
  Eraser,
  FileImage,
  FileText,
  FileType2,
  FileUp,
  Files,
  ImageIcon,
  Images,
  KeyRound,
  Languages,
  Link2,
  Minimize2,
  Percent,
  QrCode,
  Repeat,
  ScanText,
  Scissors,
  Shield,
  Trash2,
  Video,
  Wand2,
  WalletCards,
  Youtube,
} from "lucide-react";

import type { Tool, ToolCategory } from "@/types/tool";

export const categories: ToolCategory[] = [
  {
    slug: "pdf",
    title: "PDF",
    description:
      "Merge, split, compress, convert, and clean up documents with focused PDF workflows.",
    icon: FileText,
    tone: "primary",
  },
  {
    slug: "image",
    title: "Image",
    description:
      "Resize, convert, crop, compress, watermark, and refine image assets.",
    icon: ImageIcon,
    tone: "teal",
  },
  {
    slug: "media",
    title: "Media",
    description:
      "Handle everyday audio and video utilities for creators and operators.",
    icon: Video,
    tone: "rose",
  },
  {
    slug: "ai",
    title: "AI Writing",
    description:
      "Draft, summarize, translate, and polish written work with AI helpers.",
    icon: Bot,
    tone: "amber",
  },
  {
    slug: "developer",
    title: "Developer",
    description:
      "Format, inspect, encode, decode, and validate developer data quickly.",
    icon: Code2,
    tone: "primary",
  },
  {
    slug: "calculator",
    title: "Calculators",
    description:
      "Calculate dates, percentages, health metrics, and financial values.",
    icon: Calculator,
    tone: "teal",
  },
  {
    slug: "converter",
    title: "Converters",
    description:
      "Move data, units, images, and documents between practical formats.",
    icon: Repeat,
    tone: "orange",
  },
  {
    slug: "security",
    title: "Security",
    description:
      "Generate hashes, QR codes, passwords, and secure utility artifacts.",
    icon: Shield,
    tone: "rose",
  },
];

export const tools: Tool[] = [
  {
    slug: "pdf-merge",
    title: "PDF Merge",
    description: "Combine up to 20 PDF files into one ordered document.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Files,
    keywords: ["pdf", "merge", "combine", "join", "documents"],
    popular: true,
  },
  {
    slug: "pdf-split",
    title: "PDF Split",
    description: "Split a PDF into every page or selected page ranges.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Scissors,
    keywords: ["pdf", "split", "extract", "pages", "range"],
    popular: true,
  },
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    description: "Rewrite PDFs with optimized object streams to reduce size.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Minimize2,
    keywords: ["pdf", "compress", "optimize", "reduce", "size"],
    popular: true,
  },
  {
    slug: "remove-pdf-pages",
    title: "Remove Pages",
    description: "Delete selected pages from a PDF and download a clean copy.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Trash2,
    keywords: ["pdf", "remove", "delete", "pages", "clean"],
    popular: true,
  },
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert PDF pages into JPG image files on the server.",
    category: "PDF",
    categorySlug: "pdf",
    icon: FileImage,
    keywords: ["pdf", "jpg", "jpeg", "image", "convert"],
    popular: true,
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Turn JPG or PNG images into a single PDF document.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Images,
    keywords: ["jpg", "jpeg", "png", "pdf", "image"],
    popular: true,
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word",
    description: "Placeholder workflow for a managed PDF to Word service.",
    category: "PDF",
    categorySlug: "pdf",
    icon: FileType2,
    keywords: ["pdf", "word", "docx", "placeholder", "convert"],
  },
  {
    slug: "word-to-pdf",
    title: "Word to PDF",
    description: "Placeholder workflow for a managed Word to PDF service.",
    category: "PDF",
    categorySlug: "pdf",
    icon: FileUp,
    keywords: ["word", "doc", "docx", "pdf", "placeholder"],
  },
  {
    slug: "image-resize",
    title: "Image Resize",
    description: "Resize images for web, social, and product surfaces.",
    category: "Image",
    categorySlug: "image",
    icon: ImageIcon,
    keywords: ["image", "resize", "dimensions"],
    popular: true,
  },
  {
    slug: "image-crop",
    title: "Image Crop",
    description: "Crop images to precise aspect ratios and framing.",
    category: "Image",
    categorySlug: "image",
    icon: Crop,
    keywords: ["image", "crop", "aspect"],
  },
  {
    slug: "image-compress",
    title: "Image Compress",
    description: "Reduce image size while keeping a useful visual result.",
    category: "Image",
    categorySlug: "image",
    icon: Minimize2,
    keywords: ["image", "compress", "optimize"],
    popular: true,
  },
  {
    slug: "remove-background",
    title: "Remove Background",
    description: "Create clean cutouts from product and profile photos.",
    category: "Image",
    categorySlug: "image",
    icon: Eraser,
    keywords: ["image", "background", "remove"],
    popular: true,
  },
  {
    slug: "youtube-thumbnail",
    title: "YouTube Thumbnail",
    description: "Extract preview thumbnails from YouTube video links.",
    category: "Media",
    categorySlug: "media",
    icon: Youtube,
    keywords: ["youtube", "thumbnail", "media"],
  },
  {
    slug: "mp4-to-mp3",
    title: "MP4 to MP3",
    description: "Create audio files from uploaded video sources.",
    category: "Media",
    categorySlug: "media",
    icon: Video,
    keywords: ["mp4", "mp3", "audio", "video"],
  },
  {
    slug: "paraphrase",
    title: "Paraphrase",
    description: "Rewrite content with clearer structure and tone.",
    category: "AI Writing",
    categorySlug: "ai",
    icon: Wand2,
    keywords: ["ai", "rewrite", "paraphrase"],
    popular: true,
  },
  {
    slug: "summarize",
    title: "Summarize",
    description: "Condense long content into concise summaries.",
    category: "AI Writing",
    categorySlug: "ai",
    icon: ScanText,
    keywords: ["ai", "summary", "summarize"],
  },
  {
    slug: "translate",
    title: "Translate",
    description: "Translate text while preserving the original intent.",
    category: "AI Writing",
    categorySlug: "ai",
    icon: Languages,
    keywords: ["ai", "translate", "language"],
  },
  {
    slug: "json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and inspect JSON payloads.",
    category: "Developer",
    categorySlug: "developer",
    icon: Braces,
    keywords: ["json", "format", "developer"],
    popular: true,
  },
  {
    slug: "url-parser",
    title: "URL Parser",
    description: "Inspect URLs, query strings, domains, and paths.",
    category: "Developer",
    categorySlug: "developer",
    icon: Link2,
    keywords: ["url", "parser", "query"],
  },
  {
    slug: "age-calculator",
    title: "Age Calculator",
    description: "Calculate exact age from a birth date.",
    category: "Calculators",
    categorySlug: "calculator",
    icon: CalendarDays,
    keywords: ["age", "date", "calculator"],
  },
  {
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    description: "Calculate percentage change, share, and values.",
    category: "Calculators",
    categorySlug: "calculator",
    icon: Percent,
    keywords: ["percentage", "math", "calculator"],
  },
  {
    slug: "currency-converter",
    title: "Currency Converter",
    description: "Convert monetary values between selected currencies.",
    category: "Converters",
    categorySlug: "converter",
    icon: WalletCards,
    keywords: ["currency", "converter", "money"],
  },
  {
    slug: "qr-generator",
    title: "QR Generator",
    description: "Generate QR codes for URLs, text, and contact data.",
    category: "Security",
    categorySlug: "security",
    icon: QrCode,
    keywords: ["qr", "code", "security"],
  },
  {
    slug: "password-generator",
    title: "Password Generator",
    description: "Create strong passwords with configurable rules.",
    category: "Security",
    categorySlug: "security",
    icon: KeyRound,
    keywords: ["password", "security", "generator"],
    popular: true,
  },
];

export const popularTools = tools.filter((tool) => tool.popular);

export const featuredSearches = [
  "merge pdf",
  "compress pdf",
  "remove background",
  "json formatter",
  "password generator",
];

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}
