import {
  Activity,
  BadgeCheck,
  Barcode,
  Binary,
  Brain,
  Calculator,
  Calendar,
  CaseSensitive,
  ChartNoAxesColumnIncreasing,
  ClipboardCheck,
  Code2,
  Crop,
  Database,
  FileArchive,
  FileCode2,
  FileImage,
  FileJson,
  FileSearch,
  FileText,
  FileType2,
  Film,
  Fingerprint,
  Globe2,
  Hash,
  ImageIcon,
  KeyRound,
  Languages,
  Link2,
  LockKeyhole,
  Mail,
  Mic,
  Minimize2,
  PaintBucket,
  Percent,
  QrCode,
  ReceiptText,
  RefreshCcw,
  Repeat2,
  Scale,
  Scissors,
  ShieldCheck,
  Sparkles,
  SquarePen,
  TableProperties,
  Type,
  Upload,
  WandSparkles,
  Youtube,
} from "lucide-react";

import type { Tool, ToolCategory } from "@/types/tool";

export const categories: ToolCategory[] = [
  {
    title: "PDF & Documents",
    slug: "pdf",
    description: "Convert, compress, merge, split, and prepare documents for sharing.",
    icon: FileText,
    tone: "rose",
  },
  {
    title: "Image Studio",
    slug: "image",
    description: "Optimize, resize, crop, enhance, and convert images for every channel.",
    icon: ImageIcon,
    tone: "teal",
  },
  {
    title: "Video & Audio",
    slug: "video",
    description: "Download, trim, compress, and convert media without switching apps.",
    icon: Film,
    tone: "amber",
  },
  {
    title: "AI Writing",
    slug: "ai",
    description: "Draft, summarize, rewrite, polish, and repurpose content faster.",
    icon: Brain,
    tone: "primary",
  },
  {
    title: "Developer Tools",
    slug: "developer",
    description: "Format, inspect, encode, decode, and debug everyday developer data.",
    icon: Code2,
    tone: "teal",
  },
  {
    title: "Calculators",
    slug: "calculator",
    description: "Run quick calculations for finance, health, dates, and percentages.",
    icon: Calculator,
    tone: "primary",
  },
  {
    title: "Conversion",
    slug: "conversion",
    description: "Convert units, dates, text formats, and structured data in seconds.",
    icon: Repeat2,
    tone: "amber",
  },
  {
    title: "Security",
    slug: "security",
    description: "Generate passwords, hashes, QR codes, IDs, and privacy-ready assets.",
    icon: ShieldCheck,
    tone: "orange",
  },
];

export const tools: Tool[] = [
  {
    title: "PDF to Word",
    description: "Convert PDFs into editable Word documents while preserving layout.",
    icon: FileText,
    slug: "pdf-to-word",
    category: "PDF & Documents",
    categorySlug: "pdf",
    keywords: ["pdf", "word", "docx", "document"],
    popular: true,
  },
  {
    title: "Word to PDF",
    description: "Create polished PDFs from DOC and DOCX files.",
    icon: Upload,
    slug: "word-to-pdf",
    category: "PDF & Documents",
    categorySlug: "pdf",
    keywords: ["word", "pdf", "doc", "docx"],
  },
  {
    title: "Compress PDF",
    description: "Reduce large PDF files for email, portals, and archives.",
    icon: Minimize2,
    slug: "compress-pdf",
    category: "PDF & Documents",
    categorySlug: "pdf",
    keywords: ["compress", "pdf", "reduce", "size"],
    popular: true,
  },
  {
    title: "Merge PDF",
    description: "Combine multiple PDFs into a single organized document.",
    icon: FileArchive,
    slug: "merge-pdf",
    category: "PDF & Documents",
    categorySlug: "pdf",
    keywords: ["merge", "combine", "pdf"],
  },
  {
    title: "Split PDF",
    description: "Extract pages or separate a PDF into smaller files.",
    icon: Scissors,
    slug: "split-pdf",
    category: "PDF & Documents",
    categorySlug: "pdf",
    keywords: ["split", "extract", "pages", "pdf"],
  },
  {
    title: "PDF to JPG",
    description: "Export every PDF page as a sharp, shareable image.",
    icon: FileImage,
    slug: "pdf-to-jpg",
    category: "PDF & Documents",
    categorySlug: "pdf",
    keywords: ["pdf", "jpg", "image", "export"],
  },
  {
    title: "Sign PDF",
    description: "Add secure signatures and initials to document pages.",
    icon: SquarePen,
    slug: "sign-pdf",
    category: "PDF & Documents",
    categorySlug: "pdf",
    keywords: ["sign", "signature", "pdf"],
  },
  {
    title: "Compress Image",
    description: "Shrink JPG, PNG, and WebP files without visible quality loss.",
    icon: ImageIcon,
    slug: "compress-image",
    category: "Image Studio",
    categorySlug: "image",
    keywords: ["image", "compress", "jpg", "png", "webp"],
    popular: true,
  },
  {
    title: "Remove Background",
    description: "Cut out product photos and portraits with AI-assisted masking.",
    icon: WandSparkles,
    slug: "remove-background",
    category: "Image Studio",
    categorySlug: "image",
    keywords: ["background", "remove", "ai", "transparent"],
    popular: true,
  },
  {
    title: "Resize Image",
    description: "Resize images by exact pixels, presets, or percentage.",
    icon: RefreshCcw,
    slug: "resize-image",
    category: "Image Studio",
    categorySlug: "image",
    keywords: ["resize", "image", "dimensions"],
  },
  {
    title: "Crop Image",
    description: "Crop images with common aspect ratios and precise handles.",
    icon: Crop,
    slug: "crop-image",
    category: "Image Studio",
    categorySlug: "image",
    keywords: ["crop", "image", "ratio"],
  },
  {
    title: "Convert Image",
    description: "Convert between JPG, PNG, WebP, AVIF, and SVG formats.",
    icon: FileType2,
    slug: "convert-image",
    category: "Image Studio",
    categorySlug: "image",
    keywords: ["convert", "image", "format", "webp"],
  },
  {
    title: "Add Watermark",
    description: "Apply branded text or logo watermarks in batch.",
    icon: LockKeyhole,
    slug: "add-watermark",
    category: "Image Studio",
    categorySlug: "image",
    keywords: ["watermark", "image", "protect"],
  },
  {
    title: "Color Picker",
    description: "Pick, convert, and copy HEX, RGB, HSL, and OKLCH values.",
    icon: PaintBucket,
    slug: "color-picker",
    category: "Image Studio",
    categorySlug: "image",
    keywords: ["color", "picker", "hex", "rgb"],
  },
  {
    title: "YouTube Thumbnail",
    description: "Fetch HD thumbnails from public YouTube videos.",
    icon: Youtube,
    slug: "youtube-thumbnail",
    category: "Video & Audio",
    categorySlug: "video",
    keywords: ["youtube", "thumbnail", "download"],
    popular: true,
  },
  {
    title: "Instagram Downloader",
    description: "Save public reels and videos for approved reuse.",
    icon: Globe2,
    slug: "instagram-downloader",
    category: "Video & Audio",
    categorySlug: "video",
    keywords: ["instagram", "download", "reels"],
  },
  {
    title: "MP4 to MP3",
    description: "Extract clean audio tracks from uploaded video files.",
    icon: Mic,
    slug: "mp4-to-mp3",
    category: "Video & Audio",
    categorySlug: "video",
    keywords: ["mp4", "mp3", "audio", "extract"],
    popular: true,
  },
  {
    title: "Audio Trimmer",
    description: "Trim audio clips with precise start and end times.",
    icon: Scissors,
    slug: "audio-trimmer",
    category: "Video & Audio",
    categorySlug: "video",
    keywords: ["audio", "trim", "cut"],
  },
  {
    title: "Video Compressor",
    description: "Reduce video size for upload, chat, and social sharing.",
    icon: Minimize2,
    slug: "video-compressor",
    category: "Video & Audio",
    categorySlug: "video",
    keywords: ["video", "compress", "mp4"],
  },
  {
    title: "Video Converter",
    description: "Convert MP4, MOV, WebM, and AVI files into the right format.",
    icon: RefreshCcw,
    slug: "video-converter",
    category: "Video & Audio",
    categorySlug: "video",
    keywords: ["video", "convert", "format"],
  },
  {
    title: "AI Summarizer",
    description: "Turn long articles, PDFs, or notes into concise summaries.",
    icon: Sparkles,
    slug: "ai-summarizer",
    category: "AI Writing",
    categorySlug: "ai",
    keywords: ["ai", "summary", "summarize"],
    popular: true,
  },
  {
    title: "Paraphrasing Tool",
    description: "Rewrite text with clearer phrasing and consistent tone.",
    icon: Languages,
    slug: "paraphrasing-tool",
    category: "AI Writing",
    categorySlug: "ai",
    keywords: ["paraphrase", "rewrite", "ai"],
  },
  {
    title: "Grammar Fixer",
    description: "Polish grammar, punctuation, and clarity in seconds.",
    icon: ClipboardCheck,
    slug: "grammar-fixer",
    category: "AI Writing",
    categorySlug: "ai",
    keywords: ["grammar", "proofread", "writing"],
  },
  {
    title: "Email Writer",
    description: "Draft thoughtful replies, outreach, and follow-ups.",
    icon: Mail,
    slug: "email-writer",
    category: "AI Writing",
    categorySlug: "ai",
    keywords: ["email", "write", "ai"],
  },
  {
    title: "Resume Bullet Rewriter",
    description: "Rewrite resume bullets with stronger action and outcomes.",
    icon: BadgeCheck,
    slug: "resume-bullet-rewriter",
    category: "AI Writing",
    categorySlug: "ai",
    keywords: ["resume", "rewrite", "career"],
  },
  {
    title: "JSON Formatter",
    description: "Format, validate, and inspect JSON with readable structure.",
    icon: FileJson,
    slug: "json-formatter",
    category: "Developer Tools",
    categorySlug: "developer",
    keywords: ["json", "format", "validate"],
    popular: true,
  },
  {
    title: "JWT Decoder",
    description: "Decode JWT headers, payloads, and claims safely.",
    icon: KeyRound,
    slug: "jwt-decoder",
    category: "Developer Tools",
    categorySlug: "developer",
    keywords: ["jwt", "token", "decode"],
  },
  {
    title: "Regex Tester",
    description: "Test regular expressions against sample text live.",
    icon: Code2,
    slug: "regex-tester",
    category: "Developer Tools",
    categorySlug: "developer",
    keywords: ["regex", "tester", "regexp"],
  },
  {
    title: "Base64 Encoder",
    description: "Encode text or files into Base64 safely.",
    icon: Binary,
    slug: "base64-encoder",
    category: "Developer Tools",
    categorySlug: "developer",
    keywords: ["base64", "encode", "decode"],
  },
  {
    title: "URL Encoder",
    description: "Encode and decode URL strings for APIs and links.",
    icon: Link2,
    slug: "url-encoder",
    category: "Developer Tools",
    categorySlug: "developer",
    keywords: ["url", "encode", "decode"],
  },
  {
    title: "Markdown Previewer",
    description: "Preview Markdown documents with GitHub-style rendering.",
    icon: FileCode2,
    slug: "markdown-previewer",
    category: "Developer Tools",
    categorySlug: "developer",
    keywords: ["markdown", "preview", "md"],
  },
  {
    title: "Age Calculator",
    description: "Calculate exact age by years, months, days, and milestones.",
    icon: Calendar,
    slug: "age-calculator",
    category: "Calculators",
    categorySlug: "calculator",
    keywords: ["age", "birthday", "date"],
    popular: true,
  },
  {
    title: "BMI Calculator",
    description: "Estimate BMI and see the corresponding health range.",
    icon: Activity,
    slug: "bmi-calculator",
    category: "Calculators",
    categorySlug: "calculator",
    keywords: ["bmi", "health", "body mass"],
  },
  {
    title: "Percentage Calculator",
    description: "Solve percentage, increase, decrease, and ratio questions.",
    icon: Percent,
    slug: "percentage-calculator",
    category: "Calculators",
    categorySlug: "calculator",
    keywords: ["percentage", "percent", "ratio"],
    popular: true,
  },
  {
    title: "Loan EMI Calculator",
    description: "Estimate monthly payments, interest, and payoff timelines.",
    icon: ChartNoAxesColumnIncreasing,
    slug: "loan-emi-calculator",
    category: "Calculators",
    categorySlug: "calculator",
    keywords: ["loan", "emi", "payment"],
  },
  {
    title: "Currency Converter",
    description: "Convert common currency pairs with a clear rate breakdown.",
    icon: Scale,
    slug: "currency-converter",
    category: "Calculators",
    categorySlug: "calculator",
    keywords: ["currency", "exchange", "money"],
  },
  {
    title: "GST Calculator",
    description: "Add or remove GST from invoice and product prices.",
    icon: ReceiptText,
    slug: "gst-calculator",
    category: "Calculators",
    categorySlug: "calculator",
    keywords: ["gst", "tax", "invoice"],
  },
  {
    title: "Unit Converter",
    description: "Convert length, weight, temperature, volume, and more.",
    icon: Repeat2,
    slug: "unit-converter",
    category: "Conversion",
    categorySlug: "conversion",
    keywords: ["unit", "convert", "measurement"],
  },
  {
    title: "Nepali Date Converter",
    description: "Convert dates between Bikram Sambat and Gregorian calendars.",
    icon: Calendar,
    slug: "nepali-date-converter",
    category: "Conversion",
    categorySlug: "conversion",
    keywords: ["nepali", "date", "calendar", "bs", "ad"],
  },
  {
    title: "Image to Text",
    description: "Extract editable text from screenshots and scanned images.",
    icon: FileSearch,
    slug: "image-to-text",
    category: "Conversion",
    categorySlug: "conversion",
    keywords: ["ocr", "image", "text"],
    popular: true,
  },
  {
    title: "Text Case Converter",
    description: "Switch text between title, sentence, camel, and snake case.",
    icon: CaseSensitive,
    slug: "text-case-converter",
    category: "Conversion",
    categorySlug: "conversion",
    keywords: ["case", "text", "convert"],
  },
  {
    title: "CSV to JSON",
    description: "Convert spreadsheet exports into structured JSON arrays.",
    icon: TableProperties,
    slug: "csv-to-json",
    category: "Conversion",
    categorySlug: "conversion",
    keywords: ["csv", "json", "convert"],
  },
  {
    title: "Word Counter",
    description: "Count words, characters, sentences, and reading time.",
    icon: Type,
    slug: "word-counter",
    category: "Conversion",
    categorySlug: "conversion",
    keywords: ["word", "count", "text"],
  },
  {
    title: "Password Generator",
    description: "Create strong passwords with adjustable length and rules.",
    icon: Fingerprint,
    slug: "password-generator",
    category: "Security",
    categorySlug: "security",
    keywords: ["password", "generator", "secure"],
    popular: true,
  },
  {
    title: "SHA Generator",
    description: "Generate SHA-256 and SHA-512 hashes for text or files.",
    icon: Hash,
    slug: "sha-generator",
    category: "Security",
    categorySlug: "security",
    keywords: ["sha", "hash", "checksum"],
  },
  {
    title: "MD5 Generator",
    description: "Create MD5 checksums for legacy verification workflows.",
    icon: Database,
    slug: "md5-generator",
    category: "Security",
    categorySlug: "security",
    keywords: ["md5", "hash", "checksum"],
  },
  {
    title: "QR Code Generator",
    description: "Generate QR codes for links, Wi-Fi, contact cards, and text.",
    icon: QrCode,
    slug: "qr-code-generator",
    category: "Security",
    categorySlug: "security",
    keywords: ["qr", "code", "generator"],
    popular: true,
  },
  {
    title: "Barcode Generator",
    description: "Create Code 128, EAN, UPC, and inventory barcodes.",
    icon: Barcode,
    slug: "barcode-generator",
    category: "Security",
    categorySlug: "security",
    keywords: ["barcode", "generator", "ean"],
  },
  {
    title: "UUID Generator",
    description: "Generate random UUIDs for databases, events, and tests.",
    icon: KeyRound,
    slug: "uuid-generator",
    category: "Security",
    categorySlug: "security",
    keywords: ["uuid", "guid", "id"],
  },
  {
    title: "SSL Checker",
    description: "Inspect certificate validity, issuer, and expiry status.",
    icon: ShieldCheck,
    slug: "ssl-checker",
    category: "Security",
    categorySlug: "security",
    keywords: ["ssl", "certificate", "security"],
  },
  {
    title: "Privacy Policy Generator",
    description: "Create a starter privacy policy for modern web products.",
    icon: LockKeyhole,
    slug: "privacy-policy-generator",
    category: "Security",
    categorySlug: "security",
    keywords: ["privacy", "policy", "legal"],
  },
];

export const popularTools = tools.filter((tool) => tool.popular).slice(0, 10);

export const featuredSearches = [
  "PDF to Word",
  "Remove Background",
  "JSON Formatter",
  "QR Code Generator",
  "Password Generator",
  "Image to Text",
];

export function getCategoryBySlug(slug: string) {
  return categories.find((category) => category.slug === slug);
}

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}
