import {
  Bot,
  Braces,
  Calculator,
  CalendarDays,
  Code2,
  Crop,
  Eraser,
  FileImage,
  FileText,
  FileType2,
  FileUp,
  Files,
  ImageIcon,
  Images,
  KeyRound,
  Languages,
  Link2,
  Minimize2,
  Percent,
  QrCode,
  Repeat,
  ScanText,
  Scissors,
  Shield,
  Trash2,
  Video,
  Wand2,
  WalletCards,
  Youtube,
} from "lucide-react";

import type { Tool, ToolCategory, ToolCategorySlug } from "@/types/tool";

export const categories: ToolCategory[] = [
  {
    slug: "pdf",
    title: "PDF",
    description:
      "Merge, split, compress, convert, and clean up documents with focused PDF workflows.",
    icon: FileText,
    tone: "primary",
  },
  {
    slug: "image",
    title: "Image",
    description:
      "Resize, convert, crop, compress, watermark, and refine image assets.",
    icon: ImageIcon,
    tone: "teal",
  },
  {
    slug: "media",
    title: "Media",
    description:
      "Handle everyday audio and video utilities for creators and operators.",
    icon: Video,
    tone: "rose",
  },
  {
    slug: "ai",
    title: "AI Writing",
    description:
      "Draft, summarize, translate, and polish written work with AI helpers.",
    icon: Bot,
    tone: "amber",
  },
  {
    slug: "developer",
    title: "Developer",
    description:
      "Format, inspect, encode, decode, and validate developer data quickly.",
    icon: Code2,
    tone: "primary",
  },
  {
    slug: "calculator",
    title: "Calculators",
    description:
      "Calculate dates, percentages, health metrics, and financial values.",
    icon: Calculator,
    tone: "teal",
  },
  {
    slug: "converter",
    title: "Converters",
    description:
      "Move data, units, images, and documents between practical formats.",
    icon: Repeat,
    tone: "orange",
  },
  {
    slug: "security",
    title: "Security",
    description:
      "Generate hashes, QR codes, passwords, and secure utility artifacts.",
    icon: Shield,
    tone: "rose",
  },
  {
    slug: "text",
    title: "Text",
    description:
      "Count, clean, sort, transform, and generate plain text utilities.",
    icon: FileText,
    tone: "amber",
  },
  {
    slug: "seo",
    title: "SEO",
    description:
      "Create metadata, previews, crawl directives, and page analysis helpers.",
    icon: Link2,
    tone: "orange",
  },
  {
    slug: "social",
    title: "Social",
    description:
      "Download social assets and format posts, captions, and hashtags.",
    icon: Youtube,
    tone: "rose",
  },
  {
    slug: "file",
    title: "File Utilities",
    description:
      "Compress, convert, inspect, rename, archive, and compare files.",
    icon: Files,
    tone: "primary",
  },
];

const toolDescriptions: Record<ToolCategorySlug, string> = {
  pdf: "Work with focused document workflows and backend-ready processing.",
  image: "Prepare image assets with upload, preview, settings, and clean output states.",
  media: "Handle video and audio creator workflows with source controls and previews.",
  ai: "Draft, rewrite, translate, and polish content with guided AI inputs.",
  developer: "Format, validate, encode, decode, and inspect developer data quickly.",
  calculator: "Calculate everyday values with clear inputs and reusable result states.",
  converter: "Convert values between practical units, dates, currencies, and formats.",
  security: "Generate or verify secure values with configurable utility controls.",
  text: "Count, clean, sort, transform, and generate plain text in one workspace.",
  seo: "Create SEO metadata, previews, crawl files, and validation-ready outputs.",
  social: "Download social assets and prepare captions, hashtags, and formatted posts.",
  file: "Compress, convert, inspect, rename, archive, and compare everyday files.",
};

function routeTool({
  legacySlug,
  routeCategory,
  routeSlug,
  title,
  categorySlug,
  icon,
  keywords = [],
  popular,
}: {
  legacySlug?: string;
  routeCategory: string;
  routeSlug: string;
  title: string;
  categorySlug: ToolCategorySlug;
  icon: Tool["icon"];
  keywords?: string[];
  popular?: boolean;
}): Tool {
  const category = categories.find((item) => item.slug === categorySlug);

  return {
    slug: legacySlug ?? `${routeCategory}/${routeSlug}`,
    title,
    description: toolDescriptions[categorySlug],
    category: category?.title ?? "Tools",
    categorySlug,
    icon,
    keywords: [
      title.toLowerCase(),
      category?.title.toLowerCase() ?? "",
      routeCategory,
      routeSlug,
      ...routeSlug.split("-"),
      ...keywords,
    ],
    href: `/tools/${routeCategory}/${routeSlug}`,
    popular,
  };
}

const pdfTools: Tool[] = [
  {
    slug: "pdf-merge",
    title: "PDF Merge",
    description: "Combine up to 20 PDF files into one ordered document.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Files,
    keywords: ["pdf", "merge", "combine", "join", "documents"],
    popular: true,
  },
  {
    slug: "pdf-split",
    title: "PDF Split",
    description: "Split a PDF into every page or selected page ranges.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Scissors,
    keywords: ["pdf", "split", "extract", "pages", "range"],
    popular: true,
  },
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    description: "Rewrite PDFs with optimized object streams to reduce size.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Minimize2,
    keywords: ["pdf", "compress", "optimize", "reduce", "size"],
    popular: true,
  },
  {
    slug: "remove-pdf-pages",
    title: "Remove Pages",
    description: "Delete selected pages from a PDF and download a clean copy.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Trash2,
    keywords: ["pdf", "remove", "delete", "pages", "clean"],
    popular: true,
  },
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert PDF pages into JPG image files on the server.",
    category: "PDF",
    categorySlug: "pdf",
    icon: FileImage,
    keywords: ["pdf", "jpg", "jpeg", "image", "convert"],
    popular: true,
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Turn JPG or PNG images into a single PDF document.",
    category: "PDF",
    categorySlug: "pdf",
    icon: Images,
    keywords: ["jpg", "jpeg", "png", "pdf", "image"],
    popular: true,
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word",
    description: "Placeholder workflow for a managed PDF to Word service.",
    category: "PDF",
    categorySlug: "pdf",
    icon: FileType2,
    keywords: ["pdf", "word", "docx", "placeholder", "convert"],
  },
  {
    slug: "word-to-pdf",
    title: "Word to PDF",
    description: "Placeholder workflow for a managed Word to PDF service.",
    category: "PDF",
    categorySlug: "pdf",
    icon: FileUp,
    keywords: ["word", "doc", "docx", "pdf", "placeholder"],
  },
];

export const tools: Tool[] = [
  ...pdfTools,
  routeTool({ legacySlug: "image-compress", routeCategory: "image", routeSlug: "compress", title: "Compress Image", categorySlug: "image", icon: Minimize2, popular: true }),
  routeTool({ legacySlug: "image-resize", routeCategory: "image", routeSlug: "resize", title: "Resize Image", categorySlug: "image", icon: ImageIcon, popular: true }),
  routeTool({ legacySlug: "image-crop", routeCategory: "image", routeSlug: "crop", title: "Crop Image", categorySlug: "image", icon: Crop }),
  routeTool({ routeCategory: "image", routeSlug: "rotate", title: "Rotate Image", categorySlug: "image", icon: Repeat }),
  routeTool({ routeCategory: "image", routeSlug: "flip", title: "Flip Image", categorySlug: "image", icon: Repeat }),
  routeTool({ routeCategory: "image", routeSlug: "jpg-png", title: "JPG ↔ PNG", categorySlug: "image", icon: Images, keywords: ["jpg", "jpeg", "png"] }),
  routeTool({ routeCategory: "image", routeSlug: "png-webp", title: "PNG ↔ WebP", categorySlug: "image", icon: Images, keywords: ["png", "webp"] }),
  routeTool({ routeCategory: "image", routeSlug: "webp-jpg", title: "WebP ↔ JPG", categorySlug: "image", icon: Images, keywords: ["webp", "jpg", "jpeg"] }),
  routeTool({ legacySlug: "remove-background", routeCategory: "image", routeSlug: "remove-background", title: "Remove Background", categorySlug: "image", icon: Eraser, popular: true }),
  routeTool({ routeCategory: "image", routeSlug: "blur-background", title: "Blur Background", categorySlug: "image", icon: ImageIcon }),
  routeTool({ routeCategory: "image", routeSlug: "add-watermark", title: "Add Watermark", categorySlug: "image", icon: FileImage }),
  routeTool({ routeCategory: "image", routeSlug: "upscaler", title: "Image Upscaler", categorySlug: "image", icon: Wand2 }),
  routeTool({ routeCategory: "image", routeSlug: "image-to-pdf", title: "Image to PDF", categorySlug: "image", icon: FileText }),
  routeTool({ routeCategory: "image", routeSlug: "ocr-image-to-text", title: "OCR Image to Text", categorySlug: "image", icon: ScanText }),
  routeTool({ routeCategory: "image", routeSlug: "metadata-viewer", title: "Image Metadata Viewer", categorySlug: "image", icon: FileImage }),

  routeTool({ legacySlug: "youtube-thumbnail", routeCategory: "video", routeSlug: "youtube-thumbnail-downloader", title: "YouTube Thumbnail Downloader", categorySlug: "media", icon: Youtube }),
  routeTool({ routeCategory: "video", routeSlug: "instagram-video-downloader", title: "Instagram Video Downloader", categorySlug: "media", icon: Video }),
  routeTool({ routeCategory: "video", routeSlug: "tiktok-video-downloader", title: "TikTok Video Downloader", categorySlug: "media", icon: Video }),
  routeTool({ routeCategory: "video", routeSlug: "facebook-video-downloader", title: "Facebook Video Downloader", categorySlug: "media", icon: Video }),
  routeTool({ legacySlug: "mp4-to-mp3", routeCategory: "video", routeSlug: "mp4-to-mp3", title: "MP4 to MP3", categorySlug: "media", icon: Video }),
  routeTool({ routeCategory: "video", routeSlug: "audio-trimmer", title: "Audio Trimmer", categorySlug: "media", icon: Scissors }),
  routeTool({ routeCategory: "video", routeSlug: "audio-converter", title: "Audio Converter", categorySlug: "media", icon: Repeat }),
  routeTool({ routeCategory: "video", routeSlug: "video-compressor", title: "Video Compressor", categorySlug: "media", icon: Minimize2 }),
  routeTool({ routeCategory: "video", routeSlug: "video-to-gif", title: "Video to GIF", categorySlug: "media", icon: Video }),
  routeTool({ routeCategory: "video", routeSlug: "gif-to-mp4", title: "GIF to MP4", categorySlug: "media", icon: Video }),
  routeTool({ routeCategory: "video", routeSlug: "extract-audio", title: "Extract Audio", categorySlug: "media", icon: Video }),
  routeTool({ routeCategory: "video", routeSlug: "merge-audio", title: "Merge Audio", categorySlug: "media", icon: Files }),

  routeTool({ routeCategory: "ai", routeSlug: "url-summary", title: "URL Summary", categorySlug: "ai", icon: ScanText }),
  routeTool({ legacySlug: "paraphrase", routeCategory: "ai", routeSlug: "paraphraser", title: "AI Paraphraser", categorySlug: "ai", icon: Wand2, popular: true }),
  routeTool({ routeCategory: "ai", routeSlug: "grammar-checker", title: "Grammar Checker", categorySlug: "ai", icon: ScanText }),
  routeTool({ routeCategory: "ai", routeSlug: "plagiarism-checker", title: "Plagiarism Checker", categorySlug: "ai", icon: ScanText }),
  routeTool({ legacySlug: "translate", routeCategory: "ai", routeSlug: "translator", title: "AI Translator", categorySlug: "ai", icon: Languages }),
  routeTool({ routeCategory: "ai", routeSlug: "text-to-speech", title: "Text to Speech", categorySlug: "ai", icon: Bot }),
  routeTool({ routeCategory: "ai", routeSlug: "speech-to-text", title: "Speech to Text", categorySlug: "ai", icon: Bot }),
  routeTool({ routeCategory: "ai", routeSlug: "essay-writer", title: "AI Essay Writer", categorySlug: "ai", icon: Wand2 }),
  routeTool({ routeCategory: "ai", routeSlug: "email-writer", title: "AI Email Writer", categorySlug: "ai", icon: Wand2 }),
  routeTool({ routeCategory: "ai", routeSlug: "blog-generator", title: "AI Blog Generator", categorySlug: "ai", icon: Wand2 }),
  routeTool({ routeCategory: "ai", routeSlug: "title-generator", title: "AI Title Generator", categorySlug: "ai", icon: Wand2 }),
  routeTool({ routeCategory: "ai", routeSlug: "keyword-generator", title: "AI Keyword Generator", categorySlug: "ai", icon: Wand2 }),
  {
    slug: "summarize",
    title: "Summarize",
    description: "Condense long content into concise summaries.",
    category: "AI Writing",
    categorySlug: "ai",
    icon: ScanText,
    keywords: ["ai", "summary", "summarize"],
  },

  routeTool({ legacySlug: "json-formatter", routeCategory: "dev", routeSlug: "json-formatter", title: "JSON Formatter", categorySlug: "developer", icon: Braces, popular: true }),
  routeTool({ routeCategory: "dev", routeSlug: "json-validator", title: "JSON Validator", categorySlug: "developer", icon: Braces }),
  routeTool({ routeCategory: "dev", routeSlug: "base64-encoder", title: "Base64 Encoder", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "base64-decoder", title: "Base64 Decoder", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "url-encoder", title: "URL Encoder", categorySlug: "developer", icon: Link2 }),
  routeTool({ routeCategory: "dev", routeSlug: "url-decoder", title: "URL Decoder", categorySlug: "developer", icon: Link2 }),
  routeTool({ routeCategory: "dev", routeSlug: "jwt-decoder", title: "JWT Decoder", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "regex-tester", title: "Regex Tester", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "markdown-previewer", title: "Markdown Previewer", categorySlug: "developer", icon: FileText }),
  routeTool({ routeCategory: "dev", routeSlug: "html-minifier", title: "HTML Minifier", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "css-minifier", title: "CSS Minifier", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "javascript-minifier", title: "JavaScript Minifier", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "sql-formatter", title: "SQL Formatter", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "xml-formatter", title: "XML Formatter", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "yaml-formatter", title: "YAML Formatter", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "color-picker", title: "Color Picker", categorySlug: "developer", icon: Wand2 }),
  routeTool({ routeCategory: "dev", routeSlug: "hex-rgb", title: "HEX ↔ RGB", categorySlug: "developer", icon: Code2 }),
  routeTool({ routeCategory: "dev", routeSlug: "uuid-generator", title: "UUID Generator", categorySlug: "developer", icon: Code2 }),
  {
    slug: "url-parser",
    title: "URL Parser",
    description: "Inspect URLs, query strings, domains, and paths.",
    category: "Developer",
    categorySlug: "developer",
    icon: Link2,
    keywords: ["url", "parser", "query"],
  },

  routeTool({ legacySlug: "age-calculator", routeCategory: "calculators", routeSlug: "age", title: "Age Calculator", categorySlug: "calculator", icon: CalendarDays }),
  routeTool({ routeCategory: "calculators", routeSlug: "bmi", title: "BMI Calculator", categorySlug: "calculator", icon: Calculator }),
  routeTool({ legacySlug: "percentage-calculator", routeCategory: "calculators", routeSlug: "percentage", title: "Percentage Calculator", categorySlug: "calculator", icon: Percent }),
  routeTool({ routeCategory: "calculators", routeSlug: "gst", title: "GST Calculator", categorySlug: "calculator", icon: Calculator }),
  routeTool({ routeCategory: "calculators", routeSlug: "emi", title: "EMI Calculator", categorySlug: "calculator", icon: Calculator }),
  routeTool({ routeCategory: "calculators", routeSlug: "loan", title: "Loan Calculator", categorySlug: "calculator", icon: Calculator }),
  routeTool({ routeCategory: "calculators", routeSlug: "currency-converter", title: "Currency Converter", categorySlug: "calculator", icon: WalletCards }),
  routeTool({ routeCategory: "calculators", routeSlug: "unit-converter", title: "Unit Converter", categorySlug: "calculator", icon: Repeat }),
  routeTool({ routeCategory: "calculators", routeSlug: "time-zone-converter", title: "Time Zone Converter", categorySlug: "calculator", icon: CalendarDays }),
  routeTool({ routeCategory: "calculators", routeSlug: "scientific", title: "Scientific Calculator", categorySlug: "calculator", icon: Calculator }),
  routeTool({ routeCategory: "calculators", routeSlug: "date-difference", title: "Date Difference Calculator", categorySlug: "calculator", icon: CalendarDays }),
  routeTool({ routeCategory: "calculators", routeSlug: "fuel-cost", title: "Fuel Cost Calculator", categorySlug: "calculator", icon: Calculator }),

  routeTool({ routeCategory: "conversion", routeSlug: "nepali-date", title: "Nepali Date", categorySlug: "converter", icon: CalendarDays }),
  routeTool({ routeCategory: "conversion", routeSlug: "unit-converter", title: "Unit Converter", categorySlug: "converter", icon: Repeat }),
  routeTool({ legacySlug: "currency-converter", routeCategory: "conversion", routeSlug: "currency-converter", title: "Currency Converter", categorySlug: "converter", icon: WalletCards }),
  routeTool({ routeCategory: "conversion", routeSlug: "temperature-converter", title: "Temperature Converter", categorySlug: "converter", icon: Repeat }),
  routeTool({ routeCategory: "conversion", routeSlug: "length-converter", title: "Length Converter", categorySlug: "converter", icon: Repeat }),
  routeTool({ routeCategory: "conversion", routeSlug: "weight-converter", title: "Weight Converter", categorySlug: "converter", icon: Repeat }),
  routeTool({ routeCategory: "conversion", routeSlug: "speed-converter", title: "Speed Converter", categorySlug: "converter", icon: Repeat }),
  routeTool({ routeCategory: "conversion", routeSlug: "volume-converter", title: "Volume Converter", categorySlug: "converter", icon: Repeat }),
  routeTool({ routeCategory: "conversion", routeSlug: "time-converter", title: "Time Converter", categorySlug: "converter", icon: CalendarDays }),
  routeTool({ routeCategory: "conversion", routeSlug: "file-size-converter", title: "File Size Converter", categorySlug: "converter", icon: FileText }),

  routeTool({ legacySlug: "password-generator", routeCategory: "security", routeSlug: "password-generator", title: "Password Generator", categorySlug: "security", icon: KeyRound, popular: true }),
  routeTool({ routeCategory: "security", routeSlug: "password-strength-checker", title: "Password Strength Checker", categorySlug: "security", icon: KeyRound }),
  routeTool({ legacySlug: "qr-generator", routeCategory: "security", routeSlug: "qr-generator", title: "QR Generator", categorySlug: "security", icon: QrCode }),
  routeTool({ routeCategory: "security", routeSlug: "barcode-generator", title: "Barcode Generator", categorySlug: "security", icon: QrCode }),
  routeTool({ routeCategory: "security", routeSlug: "md5-generator", title: "MD5 Generator", categorySlug: "security", icon: Shield }),
  routeTool({ routeCategory: "security", routeSlug: "sha1-generator", title: "SHA-1 Generator", categorySlug: "security", icon: Shield }),
  routeTool({ routeCategory: "security", routeSlug: "sha256-generator", title: "SHA-256 Generator", categorySlug: "security", icon: Shield }),
  routeTool({ routeCategory: "security", routeSlug: "sha512-generator", title: "SHA-512 Generator", categorySlug: "security", icon: Shield }),
  routeTool({ routeCategory: "security", routeSlug: "hash-verifier", title: "Hash Verifier", categorySlug: "security", icon: Shield }),
  routeTool({ routeCategory: "security", routeSlug: "uuid-generator", title: "UUID Generator", categorySlug: "security", icon: Code2 }),
  routeTool({ routeCategory: "security", routeSlug: "random-string-generator", title: "Random String Generator", categorySlug: "security", icon: KeyRound }),
  routeTool({ routeCategory: "security", routeSlug: "secure-token-generator", title: "Secure Token Generator", categorySlug: "security", icon: KeyRound }),

  routeTool({ routeCategory: "text", routeSlug: "word-counter", title: "Word Counter", categorySlug: "text", icon: FileText }),
  routeTool({ routeCategory: "text", routeSlug: "character-counter", title: "Character Counter", categorySlug: "text", icon: FileText }),
  routeTool({ routeCategory: "text", routeSlug: "line-counter", title: "Line Counter", categorySlug: "text", icon: FileText }),
  routeTool({ routeCategory: "text", routeSlug: "case-converter", title: "Case Converter", categorySlug: "text", icon: Repeat }),
  routeTool({ routeCategory: "text", routeSlug: "remove-duplicate-lines", title: "Remove Duplicate Lines", categorySlug: "text", icon: Trash2 }),
  routeTool({ routeCategory: "text", routeSlug: "text-sorter", title: "Text Sorter", categorySlug: "text", icon: FileText }),
  routeTool({ routeCategory: "text", routeSlug: "find-replace", title: "Find & Replace", categorySlug: "text", icon: ScanText }),
  routeTool({ routeCategory: "text", routeSlug: "reverse-text", title: "Reverse Text", categorySlug: "text", icon: Repeat }),
  routeTool({ routeCategory: "text", routeSlug: "remove-extra-spaces", title: "Remove Extra Spaces", categorySlug: "text", icon: Trash2 }),
  routeTool({ routeCategory: "text", routeSlug: "lorem-ipsum-generator", title: "Lorem Ipsum Generator", categorySlug: "text", icon: FileText }),

  routeTool({ routeCategory: "seo", routeSlug: "meta-generator", title: "Meta Tag Generator", categorySlug: "seo", icon: Link2 }),
  routeTool({ routeCategory: "seo", routeSlug: "open-graph-generator", title: "Open Graph Generator", categorySlug: "seo", icon: Link2 }),
  routeTool({ routeCategory: "seo", routeSlug: "robots-generator", title: "Robots.txt Generator", categorySlug: "seo", icon: FileText }),
  routeTool({ routeCategory: "seo", routeSlug: "sitemap-generator", title: "Sitemap Generator", categorySlug: "seo", icon: FileText }),
  routeTool({ routeCategory: "seo", routeSlug: "keyword-density-checker", title: "Keyword Density Checker", categorySlug: "seo", icon: ScanText }),
  routeTool({ routeCategory: "seo", routeSlug: "seo-analyzer", title: "SEO Analyzer", categorySlug: "seo", icon: ScanText }),
  routeTool({ routeCategory: "seo", routeSlug: "google-serp-preview", title: "Google SERP Preview", categorySlug: "seo", icon: ScanText }),
  routeTool({ routeCategory: "seo", routeSlug: "canonical-url-generator", title: "Canonical URL Generator", categorySlug: "seo", icon: Link2 }),
  routeTool({ routeCategory: "seo", routeSlug: "schema-generator", title: "Schema Generator", categorySlug: "seo", icon: Code2 }),
  routeTool({ routeCategory: "seo", routeSlug: "slug-generator", title: "Slug Generator", categorySlug: "seo", icon: Link2 }),
  routeTool({ routeCategory: "seo", routeSlug: "redirect-checker", title: "Redirect Checker", categorySlug: "seo", icon: Link2 }),
  routeTool({ routeCategory: "seo", routeSlug: "broken-link-checker", title: "Broken Link Checker", categorySlug: "seo", icon: Link2 }),

  routeTool({ routeCategory: "social", routeSlug: "youtube-thumbnail-downloader", title: "YouTube Thumbnail Downloader", categorySlug: "social", icon: Youtube }),
  routeTool({ routeCategory: "social", routeSlug: "instagram-downloader", title: "Instagram Downloader", categorySlug: "social", icon: Video }),
  routeTool({ routeCategory: "social", routeSlug: "tiktok-downloader", title: "TikTok Downloader", categorySlug: "social", icon: Video }),
  routeTool({ routeCategory: "social", routeSlug: "facebook-downloader", title: "Facebook Downloader", categorySlug: "social", icon: Video }),
  routeTool({ routeCategory: "social", routeSlug: "twitter-x-downloader", title: "Twitter/X Downloader", categorySlug: "social", icon: Video }),
  routeTool({ routeCategory: "social", routeSlug: "linkedin-post-formatter", title: "LinkedIn Post Formatter", categorySlug: "social", icon: FileText }),
  routeTool({ routeCategory: "social", routeSlug: "hashtag-generator", title: "Hashtag Generator", categorySlug: "social", icon: Wand2 }),
  routeTool({ routeCategory: "social", routeSlug: "social-caption-generator", title: "Social Caption Generator", categorySlug: "social", icon: Wand2 }),

  routeTool({ routeCategory: "file", routeSlug: "zip-extractor", title: "ZIP Extractor", categorySlug: "file", icon: FileUp }),
  routeTool({ routeCategory: "file", routeSlug: "zip-creator", title: "ZIP Creator", categorySlug: "file", icon: Files }),
  routeTool({ routeCategory: "file", routeSlug: "rename-files", title: "Rename Files", categorySlug: "file", icon: FileText }),
  routeTool({ routeCategory: "file", routeSlug: "metadata-viewer", title: "File Metadata Viewer", categorySlug: "file", icon: FileText }),
  routeTool({ routeCategory: "file", routeSlug: "duplicate-file-finder", title: "Duplicate File Finder", categorySlug: "file", icon: Files }),
  routeTool({ routeCategory: "file", routeSlug: "checksum-generator", title: "File Checksum Generator", categorySlug: "file", icon: Shield }),
  routeTool({ routeCategory: "file", routeSlug: "file-compressor", title: "File Compressor", categorySlug: "file", icon: Minimize2 }),
  routeTool({ routeCategory: "file", routeSlug: "file-converter", title: "File Converter", categorySlug: "file", icon: Repeat }),
];

export const popularTools = tools.filter((tool) => tool.popular);

export const featuredSearches = [
  "merge pdf",
  "compress pdf",
  "remove background",
  "json formatter",
  "password generator",
];

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}
